version: "3"

services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo/scripts/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 27017:27017

  registry-service:
    container_name: registry-service
    restart: always
    build:
      context: ./registry-service
      dockerfile: Dockerfile
    image: barandenizkorkmaz/deployment-registry-service
    ports:
      - 8761:8761

  gateway:
    container_name: gateway
    restart: always
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: barandenizkorkmaz/deployment-gateway
    ports:
      - 10789:10789

  authentication-service:
    container_name: authentication-service
    restart: always
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    image: barandenizkorkmaz/deployment-authentication-service
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
    command: ./script.sh

  delivery-service:
    container_name: delivery-service
    restart: always
    build:
      context: ./delivery-service
      dockerfile: Dockerfile
    image: barandenizkorkmaz/deployment-delivery-service
    ports:
      - 8082:8082
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend_v2
      dockerfile: Dockerfile
    image: barandenizkorkmaz/deployment-frontend
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true