version: "3"

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  registry-service:
    container_name: registry-service
    image: barandenizkorkmaz/deployment-registry-service:latest
    restart: always
    ports:
      - 8761:8761

  gateway:
    container_name: gateway
    image: barandenizkorkmaz/deployment-gateway:latest
    restart: always
    ports:
      - 10789:10789

  authentication-service:
    container_name: authentication-service
    image: barandenizkorkmaz/deployment-authentication-service:latest
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo

  delivery-service:
    container_name: delivery-service
    image: barandenizkorkmaz/deployment-delivery-service:latest
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    image: barandenizkorkmaz/deployment-frontend:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true