version: "3"

services:
  mongo:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"

  registry-service:
    container_name: registry-service
    restart: always
    build:
      context: ./registry-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    container_name: gateway
    restart: always
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "10789:10789"

  authentication-service:
    container_name: authentication-service
    restart: always
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  delivery-service:
    container_name: delivery-service
    restart: always
    build:
      context: ./delivery-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend_v2
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true